version: '3.4'
services:
  complaint-form-email-converter-service:
    image: semtech/mu-javascript-template:1.3.2
    ports:
      - "100:80"
    links:
      - database:database
    volumes:
      - /path/to/folder/complaint-form-email-converter-service/:/app/
      - ./app/templates/:/app/templates/
  berichtencentrum-deliver-email-service:
    image: semtech/mu-javascript-template
    ports:
      - "8888:80"
      - "9229:9229"
    environment:
      NODE_ENV: "development"
      SMTP_OR_REST: "smtp"
      WELL_KNOWN_SERVICE_OR_SERVER: "SendGrid"
      EMAIL_ADDRESS: "apikey"
      EMAIL_PASSWORD: "theAppKey"
      FROM_NAME: "Agentschap Binnenlands Bestuur Vlaanderen"
    links:
      - database:database
    volumes:
      - /path/to/folder/berichtencentrum-deliver-email-service/:/app/
  identifier:
    ports:
      - "80:80"
  database:
    ports:
      - "8890:8890"
