version: '3.7'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:

  frontend:
    image: lblod/frontend-complaint-form:0.6.0
    links:
      - identifier:backend
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  identifier:
    image: semtech/mu-identifier:1.10.1
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  login:
    image: lblod/acmidm-login-service:0.11.0
    environment:
      MU_APPLICATION_AUTH_DISCOVERY_URL: "https://authenticatie-ti.vlaanderen.be/op"
      MU_APPLICATION_AUTH_CLIENT_ID: "5cbf63f8-fbd9-4ab6-8c91-be0d07723147"
      MU_APPLICATION_AUTH_REDIRECT_URI: "https://loket.lblod.info/authorization/callback"
      MU_APPLICATION_AUTH_CLIENT_SECRET: "secret"
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  dispatcher:
    image: semtech/mu-dispatcher:2.0.0
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  virtuoso:
    image: redpencil/virtuoso:1.2.0-rc.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  database:
    image: semtech/mu-authorization:0.6.0-beta.8
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
      DATABASE_OVERLOAD_RECOVERY: "true"
      DATABASE_COMPATIBILITY: "Virtuoso"
    volumes:
      - ./config/authorization:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  deltanotifier:
    image: semtech/mu-delta-notifier:0.2.0
    volumes:
      - ./config/delta-notifier:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  migrations:
    image: semtech/mu-migrations-service:0.9.0
    environment:
      MU_SPARQL_TIMEOUT: '300'
    links:
      - virtuoso:database
    volumes:
      - ./config/migrations:/data/migrations
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  resource:
    image: semtech/mu-cl-resources:1.22.2
    volumes:
      - ./config/resources:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  file:
    image: semtech/mu-file-service:3.3.2
    volumes:
      - ./data/files:/share
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  complaint-form-email-converter:
    image: lblod/complaint-form-email-converter-service:1.0.2
    volumes:
      - ./config/complaint-form-email-converter/templates:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  deliver-email:
    image: redpencil/deliver-email-service:0.3.3
    environment:
      MAILBOX_URI: 'http://data.lblod.info/id/mailboxes/1'
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  complaint-form-warning:
    image: lblod/complaint-form-warning-service:1.0.1
    #NOTE: put something like the following in the overrides
    #environment:
    #  EMAIL_FROM: person@mail.com
    #  EMAIL_TO: person@mail.com
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  error-alert:
    image: lblod/loket-error-alert-service:1.0.0
    #NOTE: put something like the following in the overrides
    #environment:
    #  EMAIL_FROM: person@mail.com
    #  EMAIL_TO: person@mail.com
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
