version: '3.7'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:

  frontend:
    image: lblod/frontend-complaint-form:0.5.2
    links:
      - identifier:backend #TODO
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  identifier:
    image: semtech/mu-identifier:1.10.1
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  dispatcher:
    image: semtech/mu-dispatcher:2.0.0
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  database:
    image: semtech/mu-authorization:0.6.0-beta.8
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
      DATABASE_OVERLOAD_RECOVERY: "true"
      DATABASE_COMPATIBILITY: "Virtuoso"
    volumes:
      - ./config/authorization:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  deltanotifier:
    image: cecemel/delta-notifier:0.2.0-beta.3
    volumes:
      - ./config/delta-notifier:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  migrations:
    image: semtech/mu-migrations-service:0.9.0
    environment:
      MU_SPARQL_TIMEOUT: '300'
    volumes:
      - ./config/migrations:/data/migrations
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  resource:
    image: semtech/mu-cl-resources:1.22.2
    volumes:
      - ./config/resources:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  file:
    image: semtech/mu-file-service:3.3.2
    volumes:
      - ./data/files:/share
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  complaint-form-email-converter-service:
    image: lblod/complaint-form-email-converter-service:0.4.0
    volumes:
      - ./config/complaint-form-email-converter/templates:/app/templates
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  deliver-email-service:
    image: redpencil/deliver-email-service:0.1.3
    environment:
      MAILBOX_URI: 'http://data.lblod.info/id/mailboxes/1'
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  complaint-form-warning:
    image: lblod/complaint-form-warning-service:0.0.3
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  error-alert:
    image: lblod/loket-error-alert-service:1.0.0
    #NOTE: put something like the following in the overrides
    #environment:
    #  EMAIL_FROM: person@mail.com
    #  EMAIL_TO: person@mail.com
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
