version: '3.7'

services:

  redirector:
    restart: "no"

  frontend:
    restart: "no"

  identifier:
    ports:
      - "80:80"
    restart: "no"

  dispatcher:
    restart: "no"

  virtuoso:
    ports:
      - "8890:8890"
    restart: "no"

  migrations:
    restart: "no"

  resource:
    restart: "no"

  file:
    restart: "no"

  mocklogin:
    image: lblod/mock-login-service:0.7.0
    restart: "no"

  complaint-form-email-converter:
    restart: "no"

  deliver-email:
    restart: "no"
    environment:
      MAILBOX_URI: 'http://data.lblod.info/id/mailboxes/1'
      WELL_KNOWN_SERVICE: "test"
      SECURE_CONNECTION: "true"
      EMAIL_ADDRESS: "mymail@test.com"
      EMAIL_PASSWORD: "myemailpassword"
      FROM_NAME: "Testmailer"
      NODE_ENV: "development"
    volumes:
      - ./data/files:/share

  complaint-form-warning:
    restart: "no"

  yasgui:
    image: erikap/yasgui:latest
    restart: "no"
    ports:
      - "89:80"
    environment:
      DEFAULT_SPARQL_ENDPOINT: "http://localhost:8890/sparql/"
      ENABLE_ENDPOINT_SELECTOR: "true"
